AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
    - '**/Gemfile'
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'rspec/**/*'
    - 'vendor/**/*'
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: False
Documentation: 
  Enabled: false
TrailingBlankLines:
  Enabled: true
MethodLength:
  Enabled: false
Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
Style/Copyright:
  Notice: '^Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: '# Copyright (c) 2016 Trilby Multimedia Ltd'
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
