language: ruby
sudo: false
cache: bundler
branches:
  only:
    - master
    - staging
env:
  matrix:
  - DATABASE_ADAPTER=postgresql
before_install:
  - echo '--colour' > ~/.rspec
services:
  - postgresql
  - redis-server
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script: 
  - bundle exec rake db:test:prepare
  - bundle exec rake
notifications:
  email: false
