default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

development:
  <<: *default
  database: webinartv_development

test:
  <<: *default
  database: webinartv_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
